### ISSUE TITLE
Work with GitHub Enterprise

### ISSUE THREAD

**Issue by hotgazpacho** [thecodejunkie/github.expandinizr#4]
It would be nice to enable adding the URL of a GitHub Enterprise instance.

**Comment by blackbarn** [comment]
Octotree has a way of doing this. Perhaps look into that. https://github.com/buunguyen/octotree

**Comment by ccampanale** [comment]
:+1: 
Just tested that functionality on Octotree and not only is it an awesome extension but the functionality with the Oauth tokens works VERY WELL. Would be a great addition to this extension!! :smile:

**Comment by gtallen1187** [comment]
Just adding another vote to include the enterprise functionality!

**Comment by khellang** [comment]
I'm not sure if any of the project's current contributors use GitHub enterprise, or even have access to an instance, so it'll be pretty hard to get something working. If anyone wants to take a stab at it, go ahead, but I don't think you'll see either me or @thecodejunkie going for this very soon :smile:

**Comment by ccampanale** [comment]
I may take a whack at it in my spare time. :wink:

**Comment by southpawlife** [comment]
+1 
I have access to a enterprise GitHub instance, and would be interested in taking a stab at it at some point as well. Currently I have a forked version of this project with the matching url's updated for our enterprise instance as a workaround.

**Comment by ccampanale** [comment]
More power to ya if you beat me to it! I haven't had time to work on this much at all.

I really want to incorporate a similar sort of feature as the one Octotree is doing to request approval to permission additional sites. I think the best route is a browser action badge with a pop-up to enter your custom enterprise URLs. Thoughts?

**Comment by ccampanale** [comment]
Scratch that: An [options page](https://developer.chrome.com/extensions/options) is probably the best bet as the last thing anyone needs are more action badges... :smile:

**Comment by ccampanale** [comment]
Finally started working on an options page in my forked repo and I think it will be a nice way of going about adding this functionality: https://github.com/ccampanale/github.expandinizr (It's not really working yet, as I only had time to lay some of the ground work.)

**Comment by thecodejunkie** [comment]
Cool :) @ccampanale could you post a screenshot so we don't have to update to the fork?

**Comment by ccampanale** [comment]
Sure thing!

Still needs some logic and what not; eventually I want to have the two defaults showing up without the button to unauthorize as you can't actually remove those.


![untitled](https://cloud.githubusercontent.com/assets/7512892/9290696/324ff5e4-436a-11e5-8712-67825e04147c.png)

**Comment by ccampanale** [comment]
Did some more work and I think it's in a nice sweet spot. I need to do some testing still but I will need to VPN in to work to do so. Once I do some tests and make sure it's working right I'll submit a pull request. 

Also wouldn't hurt if others with an enterprise Github installation tested it out to make sure it's working right. :smiley:

**Comment by hotgazpacho** [comment]
Happy to help test when you're ready, @ccampanale!

**Comment by southpawlife** [comment]
Likewise, @ccampanale.

**Comment by ccampanale** [comment]
So I realized I still needed to add something else. Since the extension currently employs listing content scripts which contain predefined "matches" settings they wouldn't get pushed to sites permissioned in the options page automatically. Instead we need to do something like OctoTree is doing by employing a background page that pushes the scripts to permissioned pages. So I made a few adjustments to the code from OctoTree and repurposed it for this extension. It still needs a little work as it will not correctly inject the CSS for the gist sites but it does seems to be working.

If you want to help me test this against your installation:
1) Clone [my repo](https://github.com/ccampanale/github.expandinizr) to `/<some-destination>/github.expandinizr/`.
2) Open [Chrome Extensions](chrom://extensions) and enable developer mode if not already enabled. (Should just be a check-box at the top.)
3) Disable stock **github.expandinizr** extension temporarily.
4) Click the "Load Unpacked Extension..." button, browse to `/<some-destination>/github.expandinizr/ext/`, and click Select.
5) Once the extension loads you will see an "Options" link in the extension which will bring you to the page where you can add permissions to the extension. 
6) Add your GHE URL. URL's added here must be formatted in the same way permissions in the manifest would be formatted which basically means make sure add include a trailing `/` or `/*` (which both evaluate the same) otherwise you will get a little error. For example: https://github.mydomain.com/ (I am thinking about including a modification to make this easier...)
7) You should see a request asking for your permission for the extension to run on that new URL and if everything goes well, it will add it to the `optional_permissions` for the extension. 
8) Test out your GHE! I've glanced through the injection code and I don't believe anything special needs to be added/changed so once added to the list of permissioned sites, it should work. Let me know if it doesn't though so I can do more research. 

Don't mind the version as I haven't bumped it yet. :P 

*Here's what it looks like on my extensions page:*
![image](https://cloud.githubusercontent.com/assets/7512892/9297739/f1437626-4471-11e5-8937-ad21d3da6d2a.png)

**Note:** You can also click the permissions link here to verify that the permissions you added are indeed added. 

**Developer note:** I've never used gulp but it looks pretty straight forward. I plan to install node and gulp and take a whack at including these new scripts so they are handled like the rest.

**Comment by southpawlife** [comment]
Tested this on GHE. Looks like it does work like you stated for GH but the Gists are not getting the css applied correctly as noted. (However the comments are working) A few other things I noticed / was thinking about. 

* While minor, when you add a new url, it adds at the bottom of the list but when the options are refreshed, it moves to its place in the list alphabetically. I don't care about what the order is, but I do think that wherever it is added initially should be the same place as when it is refreshed.

* I was also noticing that there is not the ability to disable the default GitHub urls. My initial use case that got me here was for enterprise in which we have longer names and it was more of a burden to read. I think we should have unauthorized buttons for the default two urls, but just have them included with the default install of the extension. 

All in all though the changes look good!

**Comment by ccampanale** [comment]
Thanks for testing! I will try to take a whack at the Gist functionality soon but trying to figure out the best way of approaching it still.

  - So, I think I know how I can address the first bullet which wouldn't be all that tough. Thing is, Chrome has some sort of funky way of determining the order of the `permissions.origin` array. So, as you add addresses, the order may continue to change. Not a big deal but either way, but it might take some finagling to get the custom permissions to appear in a consistent order.

  - I could easily be wrong about this but from the research I did this weekend default permissions cannot be removed. That being said, I may be able to add them to the `optional_permissions` array which would make them removable. I will have to look into this though.

Thanks again for testing this in your environment!

**Comment by ccampanale** [comment]
Definitely made some progress last night and this morning. LOTS of changes though. Had to overhaul the entire extension in regards to the code injection logic in order to flesh certain things out. I hope the developers don't mind...

The best I could do for the first bullet was making it so the two default permissions are always at the top of the list. The order of anything else added will be determined on the order that Chrome stores and returns the `permissions.origin` array. This is about the best that can be done within reason, of course.

The second bullet was what really required doing an intensive logically overhaul to the extension as you cannot include default `optional_permissions` in the manifest. Furthermore you cannot disable the required `permissions` using the standard Chrome framework. So, to work around this I had to first add storage permissions to the manifest in order to save your settings on whether the default sites should still be receiving injected code (the code that resizes the page) as well as permissions to read your tab URLs in order to write logic that utilizes the options. Ultimately, I of course wanted (rather, in my opinion needed) to maintain the original default functionality of the extension where github and gist.github were on by default.

Getting gist to work was interesting... Publicly gist is available at https://gist.github.com/ but for GHE it's at https://<server>.<domain>.<tld>/gist/. Should be working now though...

@southpawlife - If you want to go ahead and pull the head down from my repo and test it out that would be cool. I've tested it on several machines (PC and two Macs) and against my GHE installation and it seems to be working fine.

@thecodejunkie - I got node, npm, and gulp with all sub modules installed and started using it. (What a freaking awesome workflow!!!) I did notice that it bumped the version of gulp in the package.json file when I installed gulp locally, I hope this isn't an issue. Let me know if you want me to submit a pull request or if there was anything you would like changed or go over first.

**Comment by southpawlife** [comment]
Nice work @ccampanale! Some Initial testing feedback. 

 * While I have not yet tested it on GHE (not currently on a machine with access) I did try adding the URL's and ran into an issue. It seems to only allow one instance of a given domain to exist in the list. So I added https://github.company.com/* which works fine, but the subsquent https://github.company.com/gist/* could then not be added. 
  * I think, after looking into how the chrome.permissions.request() works, that I am just trying to authorize the same url twice. I will test that the gist's work tomorrow on enterprise, but I am thinking this should be fine.  (Sort of answering my own question, as I work on this comment) 

 * Tested the Enable/Disable and that seemed to work perfectly for me on github.com and gists.github.com.

 * Lastly, and minor, I would disable the add button if the url is blank, and present a message if the url has already been added. (Considering I was not aware that I was adding the same base url twice and initially figured it was an error) IMO. :smile:

**Comment by ccampanale** [comment]
Thanks!

Yeah, that is interesting but I think you are right. It probably sees those as the same URL. That being said, GHE Gist works fine from my testing but is tied to the domain. I'm not really sure how to break it out in order to be added independent of the primary GHE URL at this time. That being said, it does correctly apply the proper injection code to the gist site.

Glad the Enable/Disable and sorting works the way you pictured it!

Good idea regarding the blank URL! I'll see what I can do there. 

Currently, if you try to add a URL that is already present it is supposed to highlight the item that already exists in the list. There may be some edge cases though where it may not highlight... I'd have to think through the logic there a little bit. I wanted to make the response subtle but if you think the highlight's too subtle then a message could be added. (I try to avoid too many alerts as I think they are annoying since I have to click them so I would probably just do a little label to the right of the add button or something...)

Thanks again for the help testing this! :smiley:

**Comment by khellang** [comment]
@ccampanale Woul you mind opening up a PR? It's easier to follow the work that way :smile:

**Comment by ccampanale** [comment]
Done @khellang :smile: 

Please let me know if you have any questions, would like anything changed, or would like any explanations!

**Comment by tborychowski** [comment]
:+1:

**Comment by gtallen1187** [comment]
<kbd>+1</kbd>

**Comment by khellang** [comment]
This landed with e84c7d4a3b05c7b787a48f3f35ddd977ab4d994b and will be part of the 1.8.0 release, in time for x-mas! :santa:
